name: A workflow for Hello World file
on: push

jobs:
  build: # identifier of job
    name: Hello World action # label shown in Github when running
    runs-on: ubuntu-latest 
    steps: # sequence of operations
      - uses: actions/checkout@master # use builtin action checkout (available from a master)
      - uses: ./action-a # use custom action a
        env: # environment variables available to the action
          MY_NAME: "Mona"
